FactoryGirl.define do
  factory :user do
    sequence(:username) { |n| "User #{n}" }
    first_name "James"
    last_name "Brown"
    country
    latitude "52.417"
    longitude "16.883"
    sequence(:email) { |n| "user_#{n}@railspeople.com" }
    password "foobar12"
    password_confirmation "foobar12"
    change_password_needed false


    factory :user_facebook_auth do |u|
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:facebook_credential)
      end
    end

    factory :user_twitter_auth do |u|
      email nil
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:twitter_credential)
      end
    end

    factory :user_github_auth do |u|
      email nil
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:github_credential)
      end
    end
  end
end
