FactoryGirl.define do
  factory :user do
    sequence(:username) { |n| "User_#{n}" }
    first_name "James"
    last_name "Brown"
    country
    latitude "52.417"
    longitude "16.883"
    sequence(:email) { |n| "user_#{n}@railspeople.com" }
    password "foobar12"
    password_confirmation "foobar12"
    change_password_needed false


    factory :user_facebook_auth do |u|
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true
      country_id nil

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:facebook_credential)
      end

      factory :user_facebook_valid_profile do |u|
        latitude "52.417"
        longitude "16.883"
        country_id 1
      end
    end

    factory :user_twitter_auth do |u|
      email "1234567890@5h0u1d-change.it"
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      country_id nil
      change_password_needed true

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:twitter_credential)
      end

      factory :user_twitter_valid_profile do |u|
        latitude "52.417"
        longitude "16.883"
        sequence(:email) { |n| "user_#{n}@railspeople.com" }
        country_id 1
      end
    end

    factory :user_github_auth do |u|
      first_name nil
      last_name nil
      country_id nil
      email "1234567890@5h0u1d-change.it"
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      change_password_needed true

      u.after(:create) do |user|
        user.o_auth_credentials << FactoryGirl.create(:github_credential)
      end

      factory :user_github_valid_profile do |u|
        sequence(:first_name) { |n| "User#{n}_first_name" }
        sequence(:last_name) { |n| "User#{n}_last_name" }
        latitude "52.417"
        longitude "16.883"
        sequence(:email) { |n| "user#{n}@railspeople.com" }
        country_id 1
      end
    end
  end
end
