FactoryGirl.define do
  factory :user do
    sequence(:username) { |n| "User #{n}" }
    first_name "James"
    last_name "Brown"
    country
    latitude "52.417"
    longitude "16.883"
    sequence(:email) { |n| "user_#{n}@railspeople.com" }
    password "foobar12"
    password_confirmation "foobar12"

    factory :user_after_registration_by_socials do
      email "autogenerated@5h0u1d-change.it"
      password "autogenerated_by_system"
      password_confirmation "autogenerated_by_system"
      latitude nil
      longitude nil
      country_id 409
      change_password_needed true
    end
  end
end
